#!/bin/bash

if [ "$1" != '' ] && [ "$2" != '' ]; then
  echo "Please enter your MySQL root password: "
  read SQLROOTPW

  echo "CREATE DATABASE $1" | mysql -uroot -p$SQLROOTPW
  echo "CREATE USER '$1'@'localhost' IDENTIFIED BY '$2';" | mysql -uroot -p$SQLROOTPW
  echo "GRANT ALL ON $1.* TO '$1'@'localhost'" | mysql -uroot -p$SQLROOTPW
  echo "flush privileges" | mysql -uroot -p$SQLROOTPW
  echo "User and database called '$1' added."
elif [ "$1" = 'help' ] || [ "$1" = '' ]; then
  echo "USAGE: sudo adddb [database name] [database user password]"
  echo "Example: to create a new database just run the command 'sudo adddb mywebsite mypassword'"
fi